download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/chrisjsewell-conda-0.0.9.tar.gz
format_version: 1.0.0
name: conda
namespace: chrisjsewell
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.0.9
version_url: /api/v3/plugin/ansible/content/published/collections/index/chrisjsewell/conda/versions/0.0.9/
